/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imc;

import java.text.DecimalFormat;
import java.util.regex.Pattern;

/**
 *
 * @author daw1
 */
public class Imc extends javax.swing.JFrame {

    /**
     * Creates new form Imc
     */
    public Imc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rangos = new javax.swing.ButtonGroup();
        jPanelPesoAltura = new javax.swing.JPanel();
        labelPeso = new javax.swing.JLabel();
        campoPeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        campAltura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBoton = new javax.swing.JPanel();
        botonCalcular = new javax.swing.JButton();
        jPanelIMC = new javax.swing.JPanel();
        labelIMC = new javax.swing.JLabel();
        calculoIMC = new javax.swing.JTextField();
        jPanelRadioButton = new javax.swing.JPanel();
        radioBajo = new javax.swing.JRadioButton();
        radioNormal = new javax.swing.JRadioButton();
        radioSobre = new javax.swing.JRadioButton();
        radioObeso = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPeso.setText("peso");

        campoPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kg");

        labelAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAltura.setText("altura");

        campAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("cm");

        javax.swing.GroupLayout jPanelPesoAlturaLayout = new javax.swing.GroupLayout(jPanelPesoAltura);
        jPanelPesoAltura.setLayout(jPanelPesoAlturaLayout);
        jPanelPesoAlturaLayout.setHorizontalGroup(
            jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoAlturaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAltura)
                    .addComponent(labelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(campAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPesoAlturaLayout.setVerticalGroup(
            jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesoAlturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesoAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAltura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBotonLayout = new javax.swing.GroupLayout(jBoton);
        jBoton.setLayout(jBotonLayout);
        jBotonLayout.setHorizontalGroup(
            jBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonCalcular)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jBotonLayout.setVerticalGroup(
            jBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelIMC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIMC.setText("IMC");

        calculoIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculoIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIMCLayout = new javax.swing.GroupLayout(jPanelIMC);
        jPanelIMC.setLayout(jPanelIMCLayout);
        jPanelIMCLayout.setHorizontalGroup(
            jPanelIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIMCLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelIMC)
                .addGap(39, 39, 39)
                .addComponent(calculoIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIMCLayout.setVerticalGroup(
            jPanelIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIMCLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelIMCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculoIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIMC))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        rangos.add(radioBajo);
        radioBajo.setText("Bajo Peso");

        rangos.add(radioNormal);
        radioNormal.setText("Normal");

        rangos.add(radioSobre);
        radioSobre.setText("Sobrepeso");

        rangos.add(radioObeso);
        radioObeso.setText("Obeso");

        javax.swing.GroupLayout jPanelRadioButtonLayout = new javax.swing.GroupLayout(jPanelRadioButton);
        jPanelRadioButton.setLayout(jPanelRadioButtonLayout);
        jPanelRadioButtonLayout.setHorizontalGroup(
            jPanelRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRadioButtonLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanelRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioObeso)
                    .addComponent(radioSobre)
                    .addComponent(radioNormal)
                    .addComponent(radioBajo))
                .addGap(33, 33, 33))
        );
        jPanelRadioButtonLayout.setVerticalGroup(
            jPanelRadioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRadioButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSobre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioObeso)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIMC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBoton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPesoAltura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        DecimalFormat patron = new DecimalFormat(".##");
        String p = this.campoPeso.getText();
        String a = this.campAltura.getText();
        
        Double peso = Double.parseDouble(p);
        Double altura = Double.parseDouble(a);
        
        alturaM = Math.pow((altura / 100), 2);
        
        imc = peso / alturaM;
        this.calculoIMC.setText(patron.format(imc));
        
        if (imc < 18.00) {
            this.radioBajo.setSelected(true);
        }
        if (imc > 18.0 && imc <= 24.9) {
            this.radioNormal.setSelected(true);
        }
        if (imc > 25.0 && imc <= 30.0) {
            this.radioSobre.setSelected(true);
        }
        if (imc > 30.0) {
            this.radioObeso.setSelected(true);
        }
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void calculoIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculoIMCActionPerformed
        

    }//GEN-LAST:event_calculoIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JTextField calculoIMC;
    private javax.swing.JTextField campAltura;
    private javax.swing.JTextField campoPeso;
    private javax.swing.JPanel jBoton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelIMC;
    private javax.swing.JPanel jPanelPesoAltura;
    private javax.swing.JPanel jPanelRadioButton;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelIMC;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JRadioButton radioBajo;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioObeso;
    private javax.swing.JRadioButton radioSobre;
    private javax.swing.ButtonGroup rangos;
    // End of variables declaration//GEN-END:variables
    private Double alturaM, imc;
}
